version: "3"

services:
  gophish:
    image: gophish/gophish
    init: true
    restart: always
    volumes:
      - ./config.json:/gophish/config.json
    ports:
      - target: 3333
        published: 3333
        protocol: tcp
        mode: host
      - target: 8080
        published: 3380
        protocol: tcp
        mode: host
    networks:
      - gophish_network

  web:
    image: nginx:1.14.2-alpine
    restart: always
    volumes:
      - ./public_html:/public_html
      - ./conf.d:/etc/nginx/conf.d/
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - gophish_network

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email admin@yourdomain.com --agree-tos --no-eff-email -d yourdomain.com
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/logs/:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    networks:
      - gophish_network

  postfix:
    build:
      context: ./email-docker
      dockerfile: Dockerfile
    image: gophish_postfix
    environment:
      - SERVER_HOSTNAME=yourdomain.info
      - SERVER_IP=your_ip_address
    init: true
    restart: unless-stopped
    ports:
      - "25:25"
      - "587:1587"
      - "993:1993"
    networks:
      - gophish_network

networks:
  gophish_network:
    driver: bridge
