---
version: "2"


services:
  gophish:
    image: gophish/gophish
    init: true
    restart: always
    ports:
      - target: 3333
        published: 3333
        protocol: tcp
        mode: host
      - target: 8080
        published: 3380
        protocol: tcp
        mode: host
  postfix:
    build:
      context: ./email-docker
      dockerfile: dockerfile
    image: gophish_postfix
    init: true
    restart: always
    environment:
      - HOSTNAME=${HOSTNAME}
    ports:
      - target: "25"
        published: "1025"
        protocol: tcp
        mode: host
      - target: "587"
        published: "1587"
        protocol: tcp
        mode: host
      - target: "993"
        published: "1993"
        protocol: tcp
        mode: host

networks:
  default: